### PR TITLE
feat: Add generic tag queries

### PR DESCRIPTION
**Pull request by MaTeS72**
This pull request adds NIP-12 generic tag queries (t, r ,g) to the filters. @ryzizub @ethicnology

### CODE REVIEW

**Comment by ethicnology** [comment]
Hello, may you give more information about these tags like in which NIP are they added ?

**Comment by MaTeS72** [comment]
> Hello, may you give more information about these tags like in which NIP are they added ?



> Hello, may you give more information about these tags like in which NIP are they added ?

**Comment by ryzizub** [comment]
@ethicnology should be https://github.com/nostr-protocol/nips/blob/master/12.md

**Comment by ethicnology** [comment]
@ryzizub Ok could you extend the events class in a `src/nips/nip_012.dart` file a bit [like NIP02](https://github.com/ethicnology/dart-nostr/blob/develop/lib/src/nips/nip_002.dart), so we can differentiate the core events from what each NIP will add in the future, this way the code could be more maintainable in the future

**Comment by ryzizub** [comment]
> @ryzizub Ok could you extend the events class in a `src/nips/nip_012.dart` file a bit [like NIP02](https://github.com/ethicnology/dart-nostr/blob/develop/lib/src/nips/nip_002.dart), so we can differentiate the core events from what each NIP will add in the future, this way the code could be more maintainable in the future

@ethicnology how you image that? The change is on core event. Its not different parsing of already present tags or content, its change on fromJson toJson level.

we can do somthing like 
```
class Nip12Event extend Event
```
where we add overrides for those methods. But it would make no sense for library user to use base level event, cause it's pretty much same just missing core data

also regarding to nip02, i would suggests move from classes to extensions, its giving more flexibility and new classes are not needed cause everything would be around the core classes

**Comment by ethicnology** [comment]
@ryzizub 

> how you image that? The change is on core event. Its not different parsing of already present tags or content, its change on fromJson toJson level.

If we add to the core event all the future NIP the code will be less modular and easy to maintain, that's why I think we should keep separated the NIPs from the core Event (NIP01)

Yes something like this:
```sh
class Nip12 extend Event
```

When we do this way we can then implement Message.deserialize to return the proper Event or NIP12 event without the user need to understand the library design.
The goal would be to be able to deserialize any message with this method.
https://github.com/ethicnology/dart-nostr/blob/145ff7ad3f575500a0bb62fbee3a62ed134b4f45/lib/src/message.dart#L11 

> regarding to nip02, i would suggests move from classes to extensions, its giving more flexibility and new classes are not needed cause everything would be around the core classes

I created a static class to give the handy methods with the given stdname `Nip2` so it can still be readable when used. Of course we can do the extends way, but we should rewrite it with attributes that will return the given properties

**Comment by ethicnology** [comment]
will be closed soon if no changes

**Pull request closed without merging**
