### PR TITLE
feat: add converts for pub key

### PR DESCRIPTION
**Pull request by ryzizub**
Hey @ethicnology 👋 

I think very useful util can be possibility to convert hex key to npub and backwards. Adding those then

### CODE REVIEW

**Comment by ethicnology** [comment]
@ryzizub How hard will it be to replace [dart_bech32](https://github.com/dart-bitcoin-lib/dart-bech32) by [bech32](https://github.com/haarts/bech32) which has more contributors/reviewers ?

**Comment by ryzizub** [comment]
@ethicnology should not be hard and im in, unfortunately [bech32](https://pub.dev/packages/bech32) have old convert library. It is already in main but its missing new release on pub.dev 

There is an issue for that https://github.com/haarts/bech32/issues/6

Lets wait for that to be solved and i will update it to bech32 library

**Comment by ryzizub** [comment]
I will convert the code to bech32 library since the update is done there. Also I think it would be great to include nsec convertion and nprofile convertion. Will do those too

**Comment by ethicnology** [comment]
Solved with [NIP19](https://github.com/ethicnology/dart-nostr/blob/develop/lib/src/nips/nip_019.dart) in #30

**Pull request closed without merging**
